//	Header generated by Constructor for Palm OS¨ 1.5
//
//	Generated at 1:27:03 PM on Saturday, December 22, 2001
//
//	Generated for file: C:\My Documents\Code\Boids\Rsc\PalmBoids.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE FROM CONSTRUCTOR FOR PALM OS¨;
//	- DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name: 		"PalmBoids"
//
//	Palm App Version: 		"1.0"



//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1000, Default Button ID = 0)
#define MainOKButton                              1001	//(Left Origin = 125, Top Origin = 145, Width = 30, Height = 10, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)


//	Resource: Talt 1001
#define RomIncompatibleAlert                      1001
#define RomIncompatibleOK                         0

//	Resource: Talt 1000
#define DebugAlert                                1000
#define DebugOK                                   0

//	Resource: MBAR 1000
#define MainFormMenuBar                           1000

//	Resource: MENU 1000
#define MainOptionsMenu                           1000
#define MainOptionsAboutPalmBoids                 1000
