//	Header generated by Constructor for Pilot 1.0.2
//
//	Generated at 7:45:48 PM on Friday, October 06, 2000
//
//	Generated for file: C:\Program Files\CodeWarrior\SRC\CellulA-1\Src\CellulA_1.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE FROM CONSTRUCTOR FOR PALMPILOT;
//	- DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Pilot App Name: 		"CellulA-1"
//
//	Pilot App Version: 		"1.4"



//	Resource: tFRM 1100
#define RulesForm                                 1100	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 1100, Menu Bar ID = 0, Default Button ID = 0)
#define RulesSaveButton                           1101	//(Left Origin = 10, Top Origin = 137, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define RulesDefaultButton                        1102	//(Left Origin = 113, Top Origin = 137, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define RulesRandomButton                         1103	//(Left Origin = 57, Top Origin = 137, Width = 44, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define RulesUnnamed1104BitMap                    9000	//(Left Origin = 16, Top Origin = 64, Bitmap Resource ID = 9000, Usable = 1)
#define RulesUnnamed1105BitMap                    9001	//(Left Origin = 16, Top Origin = 80, Bitmap Resource ID = 9001, Usable = 1)
#define RulesUnnamed1106BitMap                    9002	//(Left Origin = 16, Top Origin = 96, Bitmap Resource ID = 9002, Usable = 1)
#define RulesUnnamed1107BitMap                    9003	//(Left Origin = 16, Top Origin = 112, Bitmap Resource ID = 9003, Usable = 1)
#define RulesUnnamed1108BitMap                    9004	//(Left Origin = 88, Top Origin = 64, Bitmap Resource ID = 9004, Usable = 1)
#define RulesUnnamed1109BitMap                    9005	//(Left Origin = 88, Top Origin = 80, Bitmap Resource ID = 9005, Usable = 1)
#define RulesUnnamed1110BitMap                    9006	//(Left Origin = 88, Top Origin = 96, Bitmap Resource ID = 9006, Usable = 1)
#define RulesUnnamed1111BitMap                    9007	//(Left Origin = 88, Top Origin = 112, Bitmap Resource ID = 9007, Usable = 1)
#define RulesUnnamed1129BitMap                    9010	//(Left Origin = 40, Top Origin = 48, Bitmap Resource ID = 9010, Usable = 1)
#define RulesUnnamed1130BitMap                    9011	//(Left Origin = 56, Top Origin = 48, Bitmap Resource ID = 9011, Usable = 1)
#define RulesUnnamed1131BitMap                    9010	//(Left Origin = 112, Top Origin = 48, Bitmap Resource ID = 9010, Usable = 1)
#define RulesUnnamed1132BitMap                    9011	//(Left Origin = 128, Top Origin = 48, Bitmap Resource ID = 9011, Usable = 1)
#define RulesUnnamed1128Label                     1128	//(Left Origin = 0, Top Origin = 16, Usable = 1, Font = Standard)
#define RulesLive0PushButton                      1112	//(Left Origin = 41, Top Origin = 65, Width = 12, Height = 12, Usable = 1, Group ID = 1, Font = Bold)
#define RulesDie0PushButton                       1113	//(Left Origin = 57, Top Origin = 65, Width = 12, Height = 12, Usable = 1, Group ID = 1, Font = Standard)
#define RulesLive1PushButton                      1114	//(Left Origin = 41, Top Origin = 81, Width = 12, Height = 12, Usable = 1, Group ID = 2, Font = Bold)
#define RulesDie1PushButton                       1115	//(Left Origin = 57, Top Origin = 81, Width = 12, Height = 12, Usable = 1, Group ID = 2, Font = Standard)
#define RulesLive2PushButton                      1116	//(Left Origin = 41, Top Origin = 97, Width = 12, Height = 12, Usable = 1, Group ID = 3, Font = Bold)
#define RulesDie2PushButton                       1117	//(Left Origin = 57, Top Origin = 97, Width = 12, Height = 12, Usable = 1, Group ID = 3, Font = Standard)
#define RulesLive3PushButton                      1118	//(Left Origin = 41, Top Origin = 113, Width = 12, Height = 12, Usable = 1, Group ID = 4, Font = Bold)
#define RulesDie3PushButton                       1119	//(Left Origin = 57, Top Origin = 113, Width = 12, Height = 12, Usable = 1, Group ID = 4, Font = Standard)
#define RulesLive4PushButton                      1120	//(Left Origin = 113, Top Origin = 65, Width = 12, Height = 12, Usable = 1, Group ID = 5, Font = Bold)
#define RulesDie4PushButton                       1121	//(Left Origin = 129, Top Origin = 65, Width = 12, Height = 12, Usable = 1, Group ID = 5, Font = Standard)
#define RulesLive5PushButton                      1122	//(Left Origin = 113, Top Origin = 81, Width = 12, Height = 12, Usable = 1, Group ID = 6, Font = Bold)
#define RulesDie5PushButton                       1123	//(Left Origin = 129, Top Origin = 81, Width = 12, Height = 12, Usable = 1, Group ID = 6, Font = Standard)
#define RulesLive6PushButton                      1124	//(Left Origin = 113, Top Origin = 97, Width = 12, Height = 12, Usable = 1, Group ID = 7, Font = Bold)
#define RulesDie6PushButton                       1125	//(Left Origin = 129, Top Origin = 97, Width = 12, Height = 12, Usable = 1, Group ID = 7, Font = Standard)
#define RulesLive7PushButton                      1126	//(Left Origin = 113, Top Origin = 113, Width = 12, Height = 12, Usable = 1, Group ID = 8, Font = Bold)
#define RulesDie7PushButton                       1127	//(Left Origin = 129, Top Origin = 113, Width = 12, Height = 12, Usable = 1, Group ID = 8, Font = Standard)
#define RulesFormGroupID                          1
#define RulesFormGroupID2                         2
#define RulesFormGroupID3                         3
#define RulesFormGroupID4                         4
#define RulesFormGroupID5                         5
#define RulesFormGroupID6                         6
#define RulesFormGroupID7                         7
#define RulesFormGroupID8                         8


//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 1, Save Behind = 0, Help ID = 0, Menu Bar ID = 1000, Default Button ID = 0)
#define MainRunButton                             1001	//(Left Origin = 10, Top Origin = 137, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainStopButton                            1002	//(Left Origin = 114, Top Origin = 137, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)


//	Resource: tFRM 1200
#define SeedForm                                  1200	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 1200, Menu Bar ID = 0, Default Button ID = 0)
#define SeedSaveButton                            1201	//(Left Origin = 10, Top Origin = 137, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define SeedUnnamed1202Label                      1202	//(Left Origin = 0, Top Origin = 16, Usable = 1, Font = Standard)
#define SeedRB_randomPushButton                   1203	//(Left Origin = 17, Top Origin = 41, Width = 126, Height = 14, Usable = 1, Group ID = 1, Font = Standard)
#define SeedRB_centerPushButton                   1204	//(Left Origin = 17, Top Origin = 65, Width = 126, Height = 14, Usable = 1, Group ID = 1, Font = Standard)
#define SeedRB_alternatePushButton                1205	//(Left Origin = 17, Top Origin = 89, Width = 126, Height = 14, Usable = 1, Group ID = 1, Font = Standard)
#define SeedFormGroupID                           1


//	Resource: tFRM 1300
#define AboutForm                                 1300	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 1300, Menu Bar ID = 0, Default Button ID = 0)
#define AboutOKButton                             1307	//(Left Origin = 7, Top Origin = 137, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define AboutUnnamed1303BitMap                    1301	//(Left Origin = 64, Top Origin = 64, Bitmap Resource ID = 1301, Usable = 1)
#define AboutUnnamed1304BitMap                    1302	//(Left Origin = 80, Top Origin = 64, Bitmap Resource ID = 1302, Usable = 1)
#define AboutUnnamed1305BitMap                    1303	//(Left Origin = 64, Top Origin = 80, Bitmap Resource ID = 1303, Usable = 1)
#define AboutUnnamed1306BitMap                    1304	//(Left Origin = 80, Top Origin = 80, Bitmap Resource ID = 1304, Usable = 1)
#define AboutUnnamed1301Label                     1301	//(Left Origin = 8, Top Origin = 16, Usable = 1, Font = Standard)
#define AboutUnnamed1302Label                     1302	//(Left Origin = 22, Top Origin = 101, Usable = 1, Font = Standard)


//	Resource: tFRM 1400
#define EvolutionForm                             1400	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 1400, Menu Bar ID = 0, Default Button ID = 0)
#define EvolutionSaveButton                       1404	//(Left Origin = 10, Top Origin = 137, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define EvolutionUnnamed1405Label                 1405	//(Left Origin = 0, Top Origin = 16, Usable = 1, Font = Standard)
#define EvolutionUnnamed1406Label                 1406	//(Left Origin = 0, Top Origin = 16, Usable = 1, Font = Standard)
#define EvolutionNonePushButton                   1401	//(Left Origin = 17, Top Origin = 41, Width = 126, Height = 14, Usable = 1, Group ID = 1, Font = Standard)
#define EvolutionEvery8PushButton                 1402	//(Left Origin = 17, Top Origin = 65, Width = 126, Height = 14, Usable = 1, Group ID = 1, Font = Standard)
#define EvolutionRandomPushButton                 1403	//(Left Origin = 17, Top Origin = 89, Width = 126, Height = 14, Usable = 1, Group ID = 1, Font = Standard)
#define EvolutionFormGroupID                      1


//	Resource: Talt 1100
#define ROMVersionAlert                           1100
#define ROMVersionOK                              0

//	Resource: MBAR 1000
#define OptionsMenuBar                            1000

//	Resource: MENU 1000
#define OptionsMenu                               1000
#define OptionsRules                              1000	// Command Key: R
#define OptionsEvolution                          1001	// Command Key: E
#define OptionsSeed                               1002	// Command Key: S
#define OptionsAbout                              1004	// Command Key: A

//	Resource: tSTR 1300
#define AboutHelpString                           1300	// "CellulA-1 is a simple cellula"

//	Resource: tSTR 1100
#define RulesHelpString                           1100	// "Save -  The selected rule set is applied.  Random - A random rule set is generated.  Default - The default rule set is restored."

//	Resource: tSTR 1400
#define EvolutionHelpString                       1400	// "Fixed Rule  - No Mutation Occurs.  Mutate Every Eight - The rule changes randomly every eight generations.  Random Chance - The rule has a 1/256 chance of changing each generation."

//	Resource: tSTR 1200
#define SeedHelpString                            1200	// "Random - Each cell in the seed row has a 1/32 chance of being active.  Centered Single - Only the single, central cell is active on the seed row.  Alternating - Every other cell is active on the seed row."

//	Resource: PICT 9007
#define CreatedforBitmapResourceIDBitmap          9007
//	Resource: PICT 9006
#define CreatedforBitmapResourceIDBitmap2         9006
//	Resource: PICT 9005
#define CreatedforBitmapResourceIDBitmap3         9005
//	Resource: PICT 9004
#define CreatedforBitmapResourceIDBitmap4         9004
//	Resource: PICT 9003
#define CreatedforBitmapResourceIDBitmap5         9003
//	Resource: PICT 9002
#define CreatedforBitmapResourceIDBitmap6         9002
//	Resource: PICT 9001
#define CreatedforBitmapResourceIDBitmap7         9001
//	Resource: PICT 9000
#define CreatedforBitmapResourceIDBitmap8         9000
//	Resource: PICT 1301
#define CreatedforBitmapResourceIDBitmap9         1301
//	Resource: PICT 1302
#define CreatedforBitmapResourceIDBitmap10        1302
//	Resource: PICT 1303
#define CreatedforBitmapResourceIDBitmap11        1303
//	Resource: PICT 1304
#define CreatedforBitmapResourceIDBitmap12        1304
//	Resource: PICT 9010
#define CreatedforBitmapResourceIDBitmap13        9010
//	Resource: PICT 9011
#define CreatedforBitmapResourceIDBitmap14        9011