//	Header generated by Constructor for Palm OS¨ 1.5
//
//	Generated at 1:23:12 PM on Sunday, December 23, 2001
//
//	Generated for file: C:\My Documents\Code\DotzII\Rsc\Dotz.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE FROM CONSTRUCTOR FOR PALM OS¨;
//	- DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name: 		"Dots"
//
//	Palm App Version: 		"2.0"



//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 1, Save Behind = 0, Help ID = 1000, Menu Bar ID = 1000, Default Button ID = 0)


//	Resource: tFRM 1100
#define AboutForm                                 1100	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define AboutOKButton                             1105	//(Left Origin = 115, Top Origin = 140, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define AboutTitleLabel                           1102	//(Left Origin = 61, Top Origin = 23, Usable = 1, Font = Large)
#define AboutText1Label                           1103	//(Left Origin = 23, Top Origin = 54, Usable = 1, Font = Standard)
#define AboutVersionLabel                         1104	//(Left Origin = 50, Top Origin = 104, Usable = 1, Font = Bold)


//	Resource: tFRM 1200
#define PreferencesForm                           1200	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 1, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define PreferencesOKButton                       1201	//(Left Origin = 115, Top Origin = 140, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define PreferencesLPlayersLabel                  1202	//(Left Origin = 5, Top Origin = 15, Usable = 1, Font = Standard)
#define PreferencesLColorSchemeLabel              1205	//(Left Origin = 5, Top Origin = 45, Usable = 1, Font = Standard)
#define PreferencesLSizeLabel                     1207	//(Left Origin = 5, Top Origin = 80, Usable = 0, Font = Standard)
#define PreferencesUnnamed1209Label               1209	//(Left Origin = 5, Top Origin = 100, Usable = 1, Font = Standard)
#define PreferencesLiColorsList                   1206	//(Left Origin = 93, Top Origin = 45, Width = 63, Usable = 1, Font = Standard, Visible Items = 2)
#define PreferencesPOnePushButton                 1203	//(Left Origin = 95, Top Origin = 15, Width = 30, Height = 12, Usable = 1, Group ID = 1, Font = Standard)
#define PreferencesPTwoPushButton                 1204	//(Left Origin = 125, Top Origin = 15, Width = 30, Height = 12, Usable = 1, Group ID = 1, Font = Standard)
#define PreferencesSize1PushButton                1210	//(Left Origin = 50, Top Origin = 99, Width = 20, Height = 12, Usable = 1, Group ID = 2, Font = Standard)
#define PreferencesSize2PushButton                1211	//(Left Origin = 70, Top Origin = 99, Width = 20, Height = 12, Usable = 1, Group ID = 2, Font = Standard)
#define PreferencesSize3PushButton                1212	//(Left Origin = 90, Top Origin = 99, Width = 20, Height = 12, Usable = 1, Group ID = 2, Font = Standard)
#define PreferencesSize4PushButton                1213	//(Left Origin = 110, Top Origin = 99, Width = 30, Height = 12, Usable = 1, Group ID = 2, Font = Standard)
#define PreferencesSlSizeSliderControl            1208	//(Left Origin = 50, Top Origin = 78, Width = 105, Height = 15, Usable = 0, Initial Value = 3, Minimum Value = 0, Maximum Value = 3, Page Jump Amount = 1, Thumb Bitmap = 0, Background Bitmap = 0)
#define PreferencesFormGroupID                    1
#define PreferencesFormGroupID2                   2


//	Resource: tFRM 1300
#define HiScoreForm                               1300	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define HiScoreOKButton                           1301	//(Left Origin = 115, Top Origin = 140, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define HiScoreLScoresList                        1302	//(Left Origin = 5, Top Origin = 15, Width = 147, Usable = 1, Font = Standard, Visible Items = 10)


//	Resource: tFRM 1400
#define HSUIForm                                  1400	//(Left Origin = 0, Top Origin = 40, Width = 160, Height = 60, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define HSUIOKButton                              1403	//(Left Origin = 119, Top Origin = 43, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define HSUIPlayerNameField                       1401	//(Left Origin = 5, Top Origin = 27, Width = 154, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define HSUIUnnamed1402Label                      1402	//(Left Origin = 17, Top Origin = 13, Usable = 1, Font = Standard)


//	Resource: Talt 1001
#define RomIncompatibleAlert                      1001
#define RomIncompatibleOK                         0

//	Resource: Talt 1101
#define DisplayIncompatibleAlert                  1101
#define DisplayIncompatibleOK                     0

//	Resource: Talt 1000
#define MsgAlert                                  1000
#define MsgOK                                     0

//	Resource: MBAR 1000
#define MainFormMenuBar                           1000

//	Resource: MENU 1000
#define OptionsMenu                               1000
#define OptionsNewGame                            1000	//  Command Key: N
#define OptionsPreferences                        1001	//  Command Key: P
#define OptionsAboutDotz                          1003	//  Command Key: A

//	Resource: MENU 1100
#define HighScoreMenu                             1100
#define HighScoreShowHighScores                   1100	//  Command Key: H

//	Resource: tSTR 1000
#define HelpID1000String                          1000	// "Dots is very simp"

//	Resource: PICT 1102
#define BitmapID1102Bitmap                        1102
//	Resource: PICT 1101
#define BitmapID1101Bitmap                        1101
//	Resource: PICT 1002
#define BitmapID1002Bitmap                        1002
//	Resource: PICT 1001
#define BitmapID1001Bitmap                        1001
//	Resource: PICT 1008
#define BitmapID1008Bitmap                        1008
//	Resource: PICT 1108
#define BitmapID1108Bitmap                        1108
//	Resource: taif 1100
#define PalmOS31ListIconAppIconFamily             1100

//	Resource: taif 1000
#define PalmOS31IconAppIconFamily                 1000
