//	Header generated by Constructor for Palm OS¨ 1.5
//
//	Generated at 7:38:43 PM on Thursday, July 26, 2001
//
//	Generated for file: C:\Program Files\Metrowerks\CW for Palm OS R6\SRC\Dots\Rsc\Dots.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE FROM CONSTRUCTOR FOR PALM OS¨;
//	- DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name: 		"Dots"
//
//	Palm App Version: 		"1.0"



//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 1000, Menu Bar ID = 1000, Default Button ID = 0)


//	Resource: tFRM 1100
#define OptionsForm                               1100	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 1102)
#define OptionsOKButton                           1102	//(Left Origin = 115, Top Origin = 140, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define OptionsOnePlayerCheckbox                  1101	//(Left Origin = 10, Top Origin = 25, Width = 139, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define OptionsFormGroupID                        0


//	Resource: Talt 1100
#define PalmOSAlert                               1100
#define PalmOSOK                                  0

//	Resource: Talt 1000
#define AboutAlert                                1000
#define AboutOK                                   0

//	Resource: MBAR 1000
#define MainMenuBar                               1000

//	Resource: MENU 1000
#define AboutMenu                                 1000
#define AboutAbout                                1000	//  Command Key: A
#define AboutNewGame                              1001	//  Command Key: N
#define AboutOptions                              1002	//  Command Key: O

//	Resource: tSTR 1000
#define HelpID1000String                          1000	// "Dots is very simp"

//	Resource: PICT 1101
#define BitmapID1101Bitmap                        1101
//	Resource: PICT 1102
#define BitmapID1102Bitmap                        1102
//	Resource: PICT 1002
#define BitmapID1002Bitmap                        1002
//	Resource: PICT 1001
#define BitmapID1001Bitmap                        1001
//	Resource: taif 1000
#define PalmOS31IconAppIconFamily                 1000

//	Resource: taif 1100
#define PalmOS31ListIconAppIconFamily             1100
