//	Header generated by Constructor for Palm OS¨ 1.5
//
//	Generated at 9:30:39 PM on Monday, September 03, 2001
//
//	Generated for file: C:\Program Files\Metrowerks\CW for Palm OS R6\SRC\AquaPort 3.0\Src\AquaPort.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE FROM CONSTRUCTOR FOR PALM OS¨;
//	- DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name: 		"AquaPort"
//
//	Palm App Version: 		"3.0"



//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 1, Save Behind = 0, Help ID = 1001, Menu Bar ID = 1000, Default Button ID = 0)
#define MainMainButtonRxButton                    1001	//(Left Origin = 5, Top Origin = 140, Width = 45, Height = 15, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainMainButtonDelButton                   1003	//(Left Origin = 110, Top Origin = 30, Width = 45, Height = 15, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainMainButtonViewButton                  1004	//(Left Origin = 110, Top Origin = 112, Width = 45, Height = 15, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainMainButtonBeamButton                  1008	//(Left Origin = 55, Top Origin = 140, Width = 45, Height = 15, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainDiverBitMap                           1000	//(Left Origin = 110, Top Origin = 140, Bitmap Resource ID = 1000, Usable = 1)
#define MainDownloadingBitMap                     1100	//(Left Origin = 110, Top Origin = 60, Bitmap Resource ID = 1100, Usable = 0)
#define MainBeamingBitMap                         1200	//(Left Origin = 110, Top Origin = 85, Bitmap Resource ID = 1200, Usable = 0)
#define MainMainLabelLabel                        1005	//(Left Origin = 5, Top Origin = 14, Usable = 1, Font = Standard)
#define MainMainListList                          1002	//(Left Origin = 5, Top Origin = 30, Width = 100, Usable = 1, Font = Standard, Visible Items = 9)


//	Resource: tFRM 1100
#define OptionsForm                               1100	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 1004, Menu Bar ID = 0, Default Button ID = 0)
#define OptionsOptionsButtonOKButton              1101	//(Left Origin = 10, Top Origin = 140, Width = 45, Height = 15, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define OptionsTempCheckbox                       1106	//(Left Origin = 10, Top Origin = 111, Width = 69, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define OptionsMinsCheckbox                       1109	//(Left Origin = 82, Top Origin = 111, Width = 69, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define OptionsAlrmCheckbox                       1110	//(Left Origin = 10, Top Origin = 123, Width = 69, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define OptionsOptionsLabelLabel                  1104	//(Left Origin = 10, Top Origin = 16, Usable = 1, Font = Standard)
#define OptionsUnnamed1111Label                   1111	//(Left Origin = 10, Top Origin = 71, Usable = 1, Font = Standard)
#define OptionsUnnamed1112Label                   1112	//(Left Origin = 10, Top Origin = 100, Usable = 1, Font = Standard)
#define OptionsPushDateUKPushButton               1102	//(Left Origin = 10, Top Origin = 43, Width = 139, Height = 12, Usable = 1, Group ID = 2, Font = Standard)
#define OptionsPushDateUSPushButton               1103	//(Left Origin = 10, Top Origin = 30, Width = 139, Height = 12, Usable = 1, Group ID = 2, Font = Standard)
#define OptionsPushDateNATOPushButton             1105	//(Left Origin = 10, Top Origin = 56, Width = 139, Height = 12, Usable = 1, Group ID = 2, Font = Standard)
#define OptionsPushPointPushButton                1107	//(Left Origin = 11, Top Origin = 85, Width = 68, Height = 12, Usable = 1, Group ID = 3, Font = Standard)
#define OptionsPushLinePushButton                 1108	//(Left Origin = 81, Top Origin = 85, Width = 68, Height = 12, Usable = 1, Group ID = 3, Font = Standard)
#define OptionsFormGroupID                        0
#define OptionsFormGroupID2                       2
#define OptionsFormGroupID3                       3


//	Resource: tFRM 1200
#define ViewForm                                  1200	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 1003, Menu Bar ID = 1000, Default Button ID = 0)
#define ViewViewButtonOKButton                    1201	//(Left Origin = 10, Top Origin = 140, Width = 35, Height = 15, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define ViewViewButtonToggleButton                1202	//(Left Origin = 70, Top Origin = 140, Width = 80, Height = 15, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define ViewScrollLButton                         1203	//(Left Origin = 2, Top Origin = 85, Width = 10, Height = 10, Usable = 0, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define ViewScrollRButton                         1204	//(Left Origin = 148, Top Origin = 85, Width = 10, Height = 10, Usable = 0, Anchor Left = 0, Frame = 1, Non-bold Frame = 1, Font = Standard)


//	Resource: Talt 1001
#define ROMIncompatibleAlert                      1001
#define ROMIncompatibleOK                         0

//	Resource: Talt 1003
#define ConfirmRxAlert                            1003
#define ConfirmRxOK                               0
#define ConfirmRxCancel                           1

//	Resource: Talt 1004
#define ConfirmDeleteAlert                        1004
#define ConfirmDeleteOK                           0
#define ConfirmDeleteCancel                       1

//	Resource: Talt 1005
#define SerialPortErrorAlert                      1005
#define SerialPortErrorOK                         0

//	Resource: Talt 1006
#define AboutAlert                                1006
#define AboutOK                                   0

//	Resource: Talt 1007
#define RecordExistsAlert                         1007
#define RecordExistsOK                            0

//	Resource: Talt 1008
#define NoLogAlert                                1008
#define NoLogOK                                   0

//	Resource: Talt 1009
#define NothingSelectedAlert                      1009
#define NothingSelectedOK                         0

//	Resource: Talt 2000
#define DebugAlert                                2000
#define DebugOK                                   0

//	Resource: Talt 1010
#define FreeSpaceAlert                            1010
#define FreeSpaceOK                               0

//	Resource: Talt 1000
#define IRErrorAlert                              1000
#define IRErrorOK                                 0

//	Resource: Talt 1100
#define RefuseBeamAlert                           1100
#define RefuseBeamOK                              0

//	Resource: MBAR 1000
#define MainFormMenuBar                           1000

//	Resource: MENU 1000
#define MainOptionsMenu                           1000
#define MainOptionsOptions                        1000	//  Command Key: O
#define MainOptionsAbout                          1002	//  Command Key: A

//	Resource: tSTR 1002
#define SerialErrorsHelpString                    1002	// "Serial Errors may be caused by several things:  Your watch ... 1) is not in transfer mode. 2) is not properly seated in the cradle. 3) has a low battery.  Your PalmOS device ... 4) is not properly connected to the cradle. 5) has a low battery. "

//	Resource: tSTR 1001
#define MainHelpString                            1001	// "AquaPort allows you to download and view Citizen Hyper Aqualand dive logs.  (Del.)  : Delete selected dive log. (View) : View selected dive log. ( D/L ) : Download new dive log from watch. (Beam): Beam selected dive log to other AquaLog user."

//	Resource: tSTR 1003
#define ViewHelpString                            1003	// "You can toggle between log summary, graph and raw data screens.  The log summary page gives the overview information, such as might be used to write up the dive in a lo"

//	Resource: tSTR 1004
#define OptionsHelpString                         1004	// "This screen is fairly self-explainitory.   You can select one of the 3 supported date formats.  Yo"

//	Resource: PICT 1000
#define diverBitmap                               1000
//	Resource: PICT 1202
#define beamBitmap                                1202
//	Resource: PICT 1001
#define flagBitmap                                1001
//	Resource: PICT 1004
#define flagBitmap2                               1004
//	Resource: PICT 1008
#define flagBitmap3                               1008
//	Resource: PICT 1011
#define smlFlagBitmap                             1011
//	Resource: PICT 1014
#define smlFlagBitmap2                            1014
//	Resource: PICT 1018
#define smlFlagBitmap3                            1018
//	Resource: PICT 1201
#define beamBitmap2                               1201
//	Resource: PICT 1101
#define downloadBitmap                            1101
//	Resource: PICT 1102
#define downloadBitmap2                           1102
//	Resource: tbmf 1200
#define BeamBitmapFamily                          1200

//	Resource: tbmf 1100
#define DownloadBitmapFamily                      1100

//	Resource: taif 1001
#define PalmOS35ListIconAppIconFamily             1001

//	Resource: taif 1000
#define PalmOS35IconAppIconFamily                 1000
