//	Header generated by Constructor for Pilot 1.0.2
//
//	Generated at 9:02:00 PM on Friday, October 06, 2000
//
//	Generated for file: C:\Program Files\CodeWarrior\SRC\Gun Smoke\Src\Gun Smoke.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE FROM CONSTRUCTOR FOR PALMPILOT;
//	- DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Pilot App Name: 		"Gun Smoke"
//
//	Pilot App Version: 		"1.0"



//	Resource: tFRM 1000
#define GunSmokeForm                              1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 1, Save Behind = 0, Help ID = 1000, Menu Bar ID = 1000, Default Button ID = 0)
#define GunSmokeReviewButtonButton                1001	//(Left Origin = 115, Top Origin = 141, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)


//	Resource: tFRM 1100
#define OptionsForm                               1100	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define OptionsOKButton                           1101	//(Left Origin = 110, Top Origin = 135, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define OptionsUnnamed1104Label                   1104	//(Left Origin = 10, Top Origin = 20, Usable = 1, Font = Standard)
#define OptionsBullsEyePushButton                 1102	//(Left Origin = 20, Top Origin = 70, Width = 120, Height = 15, Usable = 1, Group ID = 110, Font = Standard)
#define OptionsRunManPushButton                   1103	//(Left Origin = 20, Top Origin = 91, Width = 120, Height = 15, Usable = 1, Group ID = 110, Font = Standard)
#define OptionsFormGroupID                        110


//	Resource: tFRM 1200
#define ReportForm                                1200	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 1000)
#define ReportReportOKButton                      1201	//(Left Origin = 115, Top Origin = 140, Width = 35, Height = 10, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define ReportUnnamed1202Field                    1202	//(Left Origin = 9, Top Origin = 19, Width = 140, Height = 110, Usable = 1, Editable = 0, Underline = 1, Single Line = 0, Dynamic Size = 1, Left Justified = 1, Max Characters = 1024, Font = Standard, Auto Shift = 0, Has Scroll Bar = 1, Numeric = 0)


//	Resource: Talt 1000
#define AboutAlert                                1000
#define AboutOK                                   0

//	Resource: Talt 1200
#define ROMAlert                                  1200
#define ROMOK                                     0

//	Resource: Talt 1300
#define NoneAlert                                 1300
#define NoneOK                                    0

//	Resource: Talt 1100
#define AnalysisAlert                             1100
#define AnalysisOK                                0

//	Resource: MBAR 1000
#define OptionsMenuBar                            1000

//	Resource: MENU 1000
#define OptionsMenu                               1000
#define OptionsOptions                            1000	// Command Key: O
#define OptionsAbout                              1001	// Command Key: A

//	Resource: tSTR 1000
#define MainHelpString                            1000	// "Touch the stylus on the target representation to record your"
